### ISSUE TITLE
Please support Python 3.8 or higher version

### ISSUE THREAD

**Issue by Fanchengyan** [conda-forge/rasterio-feedstock#200]
please support Python 3.8 or higher version. I can intall rasterio in python3.7 or 3.6 easily. But when install it in Python3.8, conda will try to solving environment:

```bash
(base) PS C:\WINDOWS\system32> conda config --add channels conda-forge
(base) PS C:\WINDOWS\system32> conda config --set channel_priority strict
(base) PS C:\WINDOWS\system32> conda install rasterio
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

**Comment by xylar** [comment]
@Fanchengyan, we really do need the output from `conda list` and `conda info` requested by the default issue template to be able to help you adequately.  Please provide those.

In the meantime, could you try treating a new environment after you have done:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
It could be that your base environment contains a combination of packages from various conda channels and/or pypi.  This is why the output of `conda list` is needed.  Here is how to create new test environment to make sure you can get python 3.8 and rasterio together:
```
conda create -y -n test python=3.8 rasterio
```
If that doesn't work, definitely let us know because that would indicate something wrong with our build.  But I do not expect that will be the case.

If it does work, it probably indicates a problem with your anaconda/miniconda base environment.  A mix of packages from different channels is a likely cause.  Installing all your packages in the base environment is also not really a recommended practice because it's not really feasible to delete the environment and start over if you run into trouble.

**Comment by Fanchengyan** [comment]
Thanks for your reply. I installed rasterio successfully using your code. The previous failure may be due to the conflict with  some packages in original environment. Thank yout again. I'll close this Issues.

**Comment by xylar** [comment]
@Fanchengyan, no worries.  If you run into trouble in the future, feel free to ping me again.
