### ISSUE TITLE
rasterio compliance with GDAL 3.3.0 ?

### ISSUE THREAD

**Issue by grouny** [conda-forge/rasterio-feedstock#206]
Hi,
Currently rasterio is not compliant with GDAL 3.3.0 released few days ago.

```
conda search -c conda-forge rasterio=1.2.4=py39hbc9cc8e_3 --info
- libgdal >=3.2.2,<3.3.0a0
```
Do you expect to release a version compliant with latest version of GDAL in the coming days?
thanks

**Comment by xylar** [comment]
@grouny, thanks for pointing this out.  It looks like automatic migration to libgdal 3.3.0 had trouble.  If you look under `gdal33` on this page: https://conda-forge.org/status/, you'll see that `rasterio` is listed under `not-solvable`.  That may be because we had trouble with `proj` versions until recently.  I'll do a manual migration now and see how it goes.

**Comment by xylar** [comment]
@grouny, it doesn't look like we can migrate to gdal 3.3 until we stop building with proj 7.2.0, and that's being done because `cartopy` doesn't work with proj 8.0.x yet: https://github.com/conda-forge/cartopy-feedstock/pull/112.  So I'm afraid this isn't yet possible.

**Comment by grouny** [comment]
thanks for your answer.
I will wait for `cartopy` next release.
