### ISSUE TITLE
Which version of rasterio requires numpy==1.19.2

### ISSUE THREAD

**Issue by SouhailAB** [conda-forge/rasterio-feedstock#212]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Using tensorflow==2.5 and rasterio (last version) raises an error about the numpy==1.19.2 incompatibility.
Any help will be appreciated ! 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xylar** [comment]
@SouhailAB, we really do need the output of `conda list` and `conda info` to be able to help.  I'll see what I get just trying to install the two packages you mentioned, though.

**Comment by xylar** [comment]
@SouhailAB, I've looked into this.  It seems that `tensorflow=2.5.0` has not yet been built on `conda-forge`: https://github.com/conda-forge/tensorflow-feedstock/pull/117

If you are trying to install `tensorflow=2.5.0` from the `defaults` channel (because you have not done):
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
as recommended at https://conda-forge.org/#about, you will unfortunately often encounter incompatibilities like this because mixing packages from different channels simply is a risky business.  I suggest waiting until `tensorflow=2.5.0` is available from conda-forge.  In the meantime, you might be best off sticking with tensorflow 2.4.1 if you can.   Or you could installing `rastero=1.2.6` from conda-forge in one conda environment and `tensorflow=2.5.0` from `defaults` in another environment if that is an option for you.

**Comment by xylar** [comment]
@SouhailAB, I've just run:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -y -n test "tensorflow>=2.5.0" rasterio
```
It seems conda-forge didn't build tensorflow 2.5.0 but did build 2.6.0: https://github.com/conda-forge/tensorflow-feedstock/pull/131

This picks up:
```
numpy              conda-forge/linux-64::numpy-1.19.5-py39hdbf815f_2
rasterio           conda-forge/linux-64::rasterio-1.2.8-py39hbc4e497_0
tensorflow         conda-forge/linux-64::tensorflow-2.6.0-py39hf3d152e_0
```
I'm guessing it will pick up `rasterio 1.2.9` very soon, as we're about to build that version.

I'm closing this for now but feel free to re-open it if you run into related problems.
